### ISSUE TITLE
Course machine name length inconsistency

### ISSUE THREAD

**Issue by AlexMTaylor** [btopro/elmsln#27]
There seems to a slight inconsistency on the length of a Course's machine name. It can be entered into the CIS system with a maximum length of 16 characters. However, the drush-create-site script validates this value and throws an error if the length exceeds 12 characters.

/elmsln/scripts/drush-create-site/drush-create-site: line 124:
if [ $courselen -gt 12 ]; then
  echo " $date Course length is too long, please enter one that's less than 14 chars"
  error=1
fi

**Comment by btopro** [comment]
in typing out a name apparently you can easily get into like 64 character dbname. We can't make it 64 (and it's kind of a sanity check cause... yeah thats a long URL) as there are 11 characters in the prefix (or more but usually around 11) but maybe something more like 40 would work? We did run into this as being an issue for Wisconsin as well, let me just confirm there's nothing *bad* about it being long from a DB compatibility perspective and then I'll make the change.

**Comment by btopro** [comment]
resolved and tested in vagrant quite a bit https://github.com/btopro/elmsln/commit/23076b5801eb80c09de6d25774ee44e2fc5420b5 we now support up to 40 character long machine names and it correctly builds the user name to match. Only issue is that if there's machine name data in CIS already it will complain about the 40 characters for the widget not being able to be reverted bc data already exists
