### ISSUE TITLE
Make a marketing distribution

### ISSUE THREAD

**Issue by btopro** [btopro/elmsln#39]
This would be a way of representing everything a group that manages this architecture does. More importantly it helps keep the scope of CIS in a data driven realm / workflow and then it can be the hub people get pointed to. Marketing aspects in CIS are pretty weak to begin with so they could be pulled out into this new distro. Courses and course data could be queries and pulled into scope of the marketing system just like any other system in the network via a viable keychain.

**Comment by rickhumphries** [comment]
Yep I think I agree with this direction. Although it scares me a little now that we've got all the marketing stuff set up on our CIS its probably a good long term strategy. In terms of structure, what do you envisage online.xyz.com/course-name will become if the CIS is the 'student hub'? A breakdown of all learner progress on that course perhaps?

**Comment by btopro** [comment]
@rickhumphries from what I've seen your group is actually building the "my courses" and student hub stuff into the CIS. I'm using CIS in the same way so I'm thinking more long term direction. We wouldn't remove anything from CIS, maybe just make a better blog (or one at all) and better marketing tools and those would be dedicated to a different space.

Longer term with your eventual need to do commerce I think this dividing line will make it easier to go "oh our marketing / payment portal" and "oh our ELMSLN instance".  Right now you'd have to roll ecommerce into CIS to get the desired effect and that's a nightmare to even think about :)

**Comment by rickhumphries** [comment]
Yeh that makes perfect sense, especially with the commerce aspect which you're right, will come into play at some point. That could open up the question for a student CRM/enrolment system being built in the CIS too perhaps? We're already heading a little down this route with an improved student searching/filtering tool initially but that could also be another distribution itself!

**Comment by rickhumphries** [comment]
And in terms of namespaces, the marketing site would keep 'online.website.com' and the CIS would change to 'my.website.com'. Is that the kind of thing you're thinking?

**Comment by btopro** [comment]
I mean at some level you can fork anything / build on top of whatever components you need (re the CRM thing). This would at least open the door yes, to being able to make CIS a more robust CRM kind of a thing where as now its depending on that data from elsewhere bc of the previous scope.  But CRM could also plug into..... ... ... .. exactly, need to get stuff going then come up with changes down the road that make sense :).

In terms of name space, CIS stays at online. This is your online world within whatever company is providing you the training or whatever. The marketing site then can sit at whatever domain you want / makes sense for your company. For my group that might be elearning.psu.edu; an address completely different from the rest of the setup. For Eberly odl.address (cause that's their name).

For you it might be your setup minus the subdomains, so a high level domain that could then live on a different machine entirely :).  I think the abstraction would allow for marketing at a space that makes sense to the organization deploying the system and then the rest of the system is the same, network driven, sub-domain driven powerhouse it is currently.

marketing distro could still hit CIS for data to keep it's course list in sync tho (as an example of 'integration'). or pull back data related to last run of a course, etc.

**Comment by rickhumphries** [comment]
Yep I'm on board with this, it's the most natural direction to go down I think and it's true that we'll be wanting to hit a high level domain for marketing stuff so having that flexibility is a good call. We're also having to hide menus and stuff that relate to the marketing side of things, which don't make sense when the user is in their dashboard. So all in all - let's do this!

**Comment by btopro** [comment]
That's a plus 1 from the extended board ;)

@michael-collins  will be very happy.

will wait for mark / wisconsin to chime in but I think I know they'll be happy... especially when seeing the site we'll provide as a boiler plate ;)

**Comment by mkwisc** [comment]
I agree with this too @btopro! I think we're in the same boat as @rickhumphries with having to hide a lot of things on our online site. We do marketing on our main public website currently and CIS is serving as just a quick internal way for users to find the actual courses being offered (and link to the course sites if they forget the link).

**Comment by rickhumphries** [comment]
@btopro you should rename the title of the issue to marketing instead of marking ;)

**Comment by btopro** [comment]
Fixed, now to you know, make a whole distro :)

**Comment by btopro** [comment]
This has been resolved; We now have a dedicated marketing distribution. While it doesn't currently have direct ELMSLN integration it's not hard to engineer. It's also zurb based so it's fitting w/ our style / design criteria.  https://www.drupal.org/project/publicize

It can be taken for a test drive quickly if run in Nittany Vagrant -- https://github.com/psudug/nittany-vagrant

Sites using this marketing distribution
============================
https://odl.science.psu.edu/
https://drupal.psu.edu/
https://www.elmsln.org/
