### ISSUE TITLE
Error when attempting system setup

### ISSUE THREAD

**Issue by gkerickson** [btopro/elmsln#41]
On a new install of ELMSLN I created a course and attempted to use system setup to create a site for that course and was given this error:

Notice: Undefined index: und in cis_helper_quick_setup_page_submit() (line 885 of /var/www/elmsln/core/dslmcode/profiles/cis-7.x-1.x/modules/custom/cis_helper/cis_helper.pages.inc).

nothing else changed unfortunately

**Comment by btopro** [comment]
error mentioned should be resolved, now lets see if there's something else up :)
