### ISSUE TITLE
Enabling Guided Tour (Joyride) feature

### ISSUE THREAD

**Issue by rickhumphries** [btopro/elmsln#43]
I'd like to know how to use and customise this feature for the course outline service. As the default an administrator can view the Guided Tour tab from the Welcome Page screen and clicking this brings in some dummy content from /resources/guidedtourpage (in the CIS) and works through the Guided Tour example. 

It would be useful to know if there is an easy way of making this available for other staff roles (I can't see anything in permissions), and how this is customised.

**Comment by btopro** [comment]
The guided tour is provided via the joyride module. In looking into this I apparently have a todo to myself to make it use a permission that makes sense so now I'm elevating this to a bug :)

**Comment by btopro** [comment]
so @rickhumphries to your other question; the way to interact with it / modify / create others can be found in the context UI. If you look at the example one that's being pulled in from CIS (and modify it there) you'll see it's effectively finding things to reference and then pointing to them in order.  The drupal module providing it is http://drupal.org/project/joyride and if you need more details about it it's yet another amazing thing to come from zurb :) http://zurb.com/playground/jquery-joyride-feature-tour-plugin

**Comment by rickhumphries** [comment]
Thanks, I'll probably get a bit of time over the weekend to do some testing then I'll report back! :)
