### ISSUE TITLE
Community Development

### ISSUE THREAD

**Issue by rickhumphries** [btopro/elmsln#44]
Thought it would be good idea to find out what features other external groups involved in ELMSLN are developing so that we can learn and collaborate with each other. I'm currently the lead for the 'UK group' and now that we've got an ELMSLN deployment integrated with our current systems we're moving on in phase 2 to areas involving content creation and additional features. Our current phase 2 roadmap involves:

- Adding H5P to media instead of using ICOR (for now) as we want to manage our interactive activities in one place and use them across courses.

- Using the new xAPI/TinCan capabilities of H5P and building a bridge from this to Learning Locker so that we can report on student activity there

- Getting Open Badges to the platform by incorporating this project - https://www.drupal.org/project/openbadging

- Developing a custom facility to allow ELMSLN to scan Learning Locker for specific xAPI statements and award Badges automatically based on statements recorded by the student

- Adding a 'search students' facility so that we can look at a course and then search for students/filter them based on different criteria, and view the information you want to by adding/removing columns from the table. These views can be exported via CSV for external reporting stuff.

Anyone else working on interesting stuff?

**Comment by michael-collins** [comment]
I work in The Eberly College of Science at Penn State. We need most of what you listed.

We are planning to build some kind of fullscreen video/transcript interface, inline content question/discussions, accessible math, self-check quizzes, grading system, calendar, student roster, student discussion forums, student blogs, internal messaging/inbox, virtual science labs, etc. I'd be interested in collaborating on anything.

We'll probably be working closely with @btopro on most of these items.

**Comment by tewnet** [comment]
I have a small elearning company that develops off-the-shelf drug and alcohol compliance training (www.drugfreebiz.com). We also develop custom courses for corporate clients. We have begun building a Drupal-based learning content component management system (LCCMS) to manage learning content at a granular level. The system will have several components: learning object repository, course authoring, course assembly, workflow management, dynamic content delivery and multi-platform course publishing. We are looking at including H5P for interactive content development. And incorporating the xAPI. We'd like to integrate the system with an LRS for reporting and LMSs for course delivery and student and course management. We're talking with @btpro about integrating with elsmln. We want this to be a completely open source Drupal initiative. 

Welcome discussion and collaboration on any and all aspects.

**Comment by rickhumphries** [comment]
We need most of what you've mentioned too @michael-collins so that's awesome :) We've already made a bit of a start on the messaging/inbox type thing by using the Privatemsg module (https://www.drupal.org/project/privatemsg) and restricting this to only let staff/admin message students (for course updates and stuff). For inline content things have you seen the Adapt framework? (https://community.adaptlearning.org/) It's not Drupal, but it is open source, so not sure whether you'd be able to get any ideas out of this as I think they do a pretty good job with showcasing inline content.

I think I know the type of thing you're thinking of @tewnet - we deliver continuing education too so would be interested in seeing how you progress

**Comment by garemoko** [comment]
@rickhumphries I notice that you're looking at implementing both xAPI and Open Badges. That's awesome! It may be worth your time looking at the work being done [here](https://github.com/ht2/BadgesCoP/tree/master/earning) to define how Open Badges can be stored and transmitted via xAPI.

**Comment by rickhumphries** [comment]
Hey @garemoko yeh I've been keeping my eye on developments there. I was actually planning on getting in touch with you soon to pick your brains as I think the stuff we're doing initially is a bit more on the evidence and criteria side of things, which I noticed there was a bit of talk in gitter about recently. We'll definitely be looking to keep to those standards in the CoP though :)

**Comment by michael-collins** [comment]
@rickhumphries Just checked out adaptlearning, looks nice, thanks for sharing. We are going to start working on some UI for some of these things. I'll send out links to the mockups for feedback when I get them done if you are interested.

**Comment by rickhumphries** [comment]
Always interested @michael-collins :)

**Comment by btopro** [comment]
converging into #72
