### ISSUE TITLE
Where are the sites for the courses I created?

### ISSUE THREAD

**Issue by gkerickson** [btopro/elmsln#45]
Where in the directory structure are new courses stored? Should the course object in my CIS link directly to that website or do I have to create that connection myself?

**Comment by btopro** [comment]
After you create a course in CIS, you're just setting up a data point that things can relate to (basically). To actually make a drupal site(s) for this, you'll want to click either the services tab on the node for the course OR do the System Setup (top right, preferred method). This creates the service instance, which will actually go and build a drupal site and then network it back into CIS to start pulling data.
