### ISSUE TITLE
What am I looking at after a new installation of ELMSLN?

### ISSUE THREAD

**Issue by gkerickson** [btopro/elmsln#46]
After a successful first installation of ELMSLN what am I looking at when I open my new site? If the purpose of ELMSLN is to be able to create many individual sites and tie them all together then what unique functionality does my first site have?

**Comment by btopro** [comment]
ELMSLN's installer sets up two kinds of systems; authorities and services. Authorities form their addresses the same way was services, they just have single drupal sites' powering them.

For example, during install CIS, ELMSMedia, and ECD are all setup as authority distributions. ELMSMedia is the asset management for example, so if I wanted to find the media for course named sing100, i'd go to media.elmsln.local/sing100. This is an authority though so sing100 is a node in the media system and not a full blown site.

courses, studio, interact, blog, and discuss are all service distros, so you're creating a service instance in CIS which then builds a drupal site at discuss.elmsln.local/sing100. In this case, sing100 is a new drupal site as a service of the discussion tool.

It's important to note that various parts are under active development (like a lot of it) but the infrastructure is providing support to do all these things. Right now CIS(online) and MOOC(courses) have the most time invested in them; as a result we run them in production in my unit and others.

After install of the system, you go to online.elmsln.local and log into the CIS
