### ISSUE TITLE
What is a course?

### ISSUE THREAD

**Issue by gkerickson** [btopro/elmsln#47]
When I create a course from the CIS all this does is create a node. How do I create a unique site for my course? Does this have to do with services?

**Comment by michael-collins** [comment]
A "course" is comprised of a cluster of services. You have to create a service. Typically the course outline is the first thing you would want to make. Go to the course node, click on the services tab, and then click: Add `Course outline` service. A Drupal site will then build out (~3 minutes) and email you when it's done. This process is a bit confusing, so we are eventually going to make this a lot more clear. Until then, that should get you started.

**Comment by btopro** [comment]
I made a wikipage to start to address this -- https://github.com/btopro/elmsln/wiki/Information-Architecture
