### ISSUE TITLE
handsfree drush-create-site issue

### ISSUE THREAD

**Issue by btopro** [btopro/elmsln#54]
after running handsfree installer,  it seems like you need to process running /usr/local/bin/drush-create-site/drush-create-site manually on the server and it works; if you let the crontab pick it up it fails... even tho both are root.... very odd.

**Comment by btopro** [comment]
mail: command not found
@bradfisher isn't there something that can be used to squash this issue / simular mail handling if mail command isn't native to the OS?

**Comment by bradallenfisher** [comment]
the os has to have some kind of mta. whether it be postfix, sendmail etc...,  without "something" the OS won't be able to:
Send mail from your users to an external MTA (another mail server) or 
Receive mail from an external MTA

**Comment by btopro** [comment]
isn't there a way to fake that? I've seen it in other's vagrant scripts

**Comment by bradallenfisher** [comment]
so like NOT send the email? just simulate it ... i see. maybe. checking on it

**Comment by btopro** [comment]
unless you know how to install a mail server on demand? Also have a question for you about crontab / bashrc sourcing hand off issue (potentially)

**Comment by btopro** [comment]
Will spin mail off to another thread. issue at hand...
https://github.com/btopro/elmsln/blob/master/scripts/install/root/elmsln-preinstall.sh sets crontab in motion w/ root calls to the drush-create-site script. This happens prior to drush being sourced into that thread's bashrc path meaning it won't realize it has access to drush until after it spins back up.

Either we can source at the start of the drush-create-site script (just to be safe in case there are future changes). Or, we can change the order of the preinstall script to avoid this issue.

Going to make a commit to try and resolve both

**Comment by btopro** [comment]
didn't fix it; rebooting server also didn't trigger it. still builds correctly if executed by user directly, just not automatically; must be something in its ability to access drush.

**Comment by btopro** [comment]
found it; want a better solution tho - we need to sed where PATH is located in crontab and then write /root/.composer/vendor/bin into the path. This will allow crontab environment to have knowledge of root being installed. Also HOME is / instead of /root/ so all things referencing home would fail in theory

**Comment by btopro** [comment]
even easier, HOME was set to / by default. if its set to /root/ it'll work :)
