### ISSUE TITLE
roll new ux across everything

### ISSUE THREAD

**Issue by btopro** [btopro/elmsln#57]
Its almost ready :)

**Comment by rickhumphries** [comment]
Yeeeeeh!

**Comment by btopro** [comment]
https://www.youtube.com/watch?v=1KB1bdDwA_k latest status check in.

**Comment by btopro** [comment]
Currently in the minor tweaks mode; @michael-collins is making it looks beyond good now. I'll be merging a new version into the repo of the project soon tho it won't be hooked up to the default installl of the distros til probably the end of the month. Need to package settings in context for block positioning, work on some accessibility and other settings.

**Comment by btopro** [comment]
https://www.youtube.com/watch?v=YrS5yPCbdbM latest check in

**Comment by btopro** [comment]
still on track, most of the work is done, starting to pair this with the overhaul needed in #66 and will need #70 to be working so I can do all the testing required. OOTB it's getting pretty close to standing up with foundation access everywhere already and the usability / block positioning making sence OOTB. Again, still things to fix but the UX branch is getting close. It is a radical step forward in design and stabilization of various components so bare with us.  The upgrade routine needs to be tested HEAVILY to transform from current to foundation access. There's also a #58 which will be the basis of the transformation. We don't want to force the overhaul via an update hook as that could cause unexpected results for downstream users (like people using custom themes which we have many doing here). All new things produced / new instances WILL have the UX OOTB though so it's more a phase in for things that currently exist. #70 will make it easy to test these changes on a mirror of a live instance in vagrant.

**Comment by btopro** [comment]
"everything" is optional so there will be a command for all legacy things to stage them over to the new UX. CIS transition is the last major one as reported in #75
