### ISSUE TITLE
Connecting CIS to courses

### ISSUE THREAD

**Issue by gkerickson** [btopro/elmsln#63]
Now that I've created several courses I'd like to access them. As far as I can tell creating a course node in my CIS doesn't necessarily link to my course site in any way. How is it that these sites tie together?

**Comment by btopro** [comment]
So after courses are created you need to create a service instance. If you go to the services tab off of a node you should be able to request services to be built for each course.  You could also use the long form in the top right to kick spaces out.


As far as authentication is concerned, if you look to how the ELMSLN Vagrant instance works you can see how you can tell new services that are created to automatically do certain drush tasks (like enabling shib and setting default settings correctly).

https://github.com/btopro/elmsln-config-vagrant/blob/master/shared/drupal-7.x/modules/vagrant/vagrant_cis_dev/vagrant_cis_dev.module

**Comment by gkerickson** [comment]
Before I have shibboleth set up on a site or have configured drush to do anything I don't have access to the site. For example I've create a course first and when I attempt to access courses.lawclinics.wisc.edu/first I receive an access denied message and can go no further. Is there any way to manage the site with the drupal interface after I've created the site without using drush?
