### ISSUE TITLE
CIS - where is the campus list being pulled from?

### ISSUE THREAD

**Issue by rickhumphries** [btopro/elmsln#64]
I thought I'd use the following link in the CIS to add a new course offering: /cis-add-offering however, through this route 'campus' is a required field. The dropdown menu is pre-populated but I can't see where this information is coming from as I'd want to alter it. Anyone have any ideas? Thanks

**Comment by btopro** [comment]
admin/structure/field-collections/field-sections/fields in the CIS system. this is one of those unfortunate points where it's hard to find a balance between supplying defaults in a packaged form and making them make any sense what so ever :). If you update the field's available values it should propagate to that other place.
