### ISSUE TITLE
Project branding / imagery

### ISSUE THREAD

**Issue by btopro** [btopro/elmsln#73]
So, elmsln.org got a massive upgrade recently, the UX is getting very close (we successfully upgraded the UX of an instance via a single command) and all new courses created currently have this UX (in the UX branch at least). The next thing to elicit feedback on in the area of UX is the representation of the ELMSLN brand.

Proposed image / textual representation / font here: https://twitter.com/elmsln/status/598469733470642176

An animation to illustrate the concept of self-building networks:
https://www.youtube.com/watch?v=9PXCUdVkOWU

Also note the background on said twitter account has a screen from the animation. Variants of the organic building snowflakes can be seen here:
https://www.elmsln.org/blog/post/opened-2014
https://www.elmsln.org/blog/post/building-drupal-based-lms-educational-institutions
https://drupal.psu.edu/blog/post/year-2020
https://drupal.psu.edu/blog/post/elmsln-year-end-review

**Comment by rickhumphries** [comment]
Really like the font/textual representation. Not sure about the leaf. Think I prefer the hexagonal snowflake type thing.

**Comment by mkwisc** [comment]
I agree with @rickhumphries. Any possible options using the hexagonal snowflake thing? Or with a different leaf design?

**Comment by michael-collins** [comment]
Open to other ideas. @btopro and I talked about how this leaf design was NOT the final logo. People responded positively to the typography, so unless someone has a better design, that will probably stay the same. I'll work on some new designs and post to slack.

**Comment by btopro** [comment]
Temporary since the snowflake was liked and Mike's going to be making it prominent in the UX overhaul --- https://twitter.com/elmsln

**Comment by btopro** [comment]
Collins has this pretty well established now at least as a draft. We can start utilizing on different outlets when we reference the project. Thanks community for input. Snowflakes reign on!

**Comment by btopro** [comment]
github project page now has this:

![ELMSLN](https://raw.githubusercontent.com/btopro/elmsln/master/docs/assets/brand1.png "ELMS Learning Network")
