### ISSUE TITLE
Embedding Images from Media

### ISSUE THREAD

**Issue by rickhumphries** [btopro/elmsln#74]
I'm having a bit of trouble getting images embedded into my course outline and resizing properly for all screen sizes.

Ideally I'd want the image to scale to the size of the iframe itself (from the embed code) and therefore it would scale as needed in the course outline. However using the embed code from Media, the iframe will scale but the image itself doesn't - it's original size remains fixed.

This either means the image won't scale to fit the page as intended, or the iframe will cut into the image on small screen sizes.

What's the best way to handle this issue? Not sure if I'm missing anything simple

Thanks

**Comment by btopro** [comment]
you embedded via iframe method, did you explore the other shortcode embed options that allow direct injection of the image? Basically it'll do the webservice lookup, realize it's an image url, and then turn itself into an <img tag; if you use that method of embedding.

Make sure CIS shortcodes is enabled on the media site and it'll give you options other then just iframe which will help to start. Then if its just an image in the local space you have more options as far as how that's handled (even just making it % based to be quazi responsive)

**Comment by rickhumphries** [comment]
Ah great - that's useful. I hadn't explored the other options. The 'Shortcode direct iframe' works but the 'image field: render image' didn't.

So the shortcode direct iframe is [ciscode|rev=1|tool=elmsmedia|item=20]

How would I make this % based now? I've tried [ciscode|rev=1|tool=elmsmedia|item=20|width=100%] out of hope but that didn't work

**Comment by btopro** [comment]
oh... lol now this turned into a bug report ;) maybe @michael-collins knows a good way to handle making images from Media responsive.

**Comment by michael-collins** [comment]
I do: http://foundation.zurb.com/docs/components/flex_video.html We need to get this into the template somewhere though...

**Comment by michael-collins** [comment]
You can wrap the shortcodes in a <div class="flex-video"></div>. It should work with most media types, but I'd like to get this into the template before the shortcodes are generated. It's on the todo list.

**Comment by rickhumphries** [comment]
I've just tried with an image e.g. 

<div class="flex-video">[ciscode|rev=1|tool=elmsmedia|item=22]
</div>

And also

<div class="flex-video"><iframe width="100%" height="300" src="http://media.buttercups.orangebusstaging.co.uk/entity_iframe/node/22" frameborder="0" class="entity_iframe entity_iframe_node" id="entity_iframe_node_22"></iframe>
</div>

But again, the image is being cut out rather than resizing

**Comment by btopro** [comment]
@michael-collins we could def make the template it generates wrap in that automatically for video; rick can you post a short video  of what that that's doing (or screen shot at snap points or something)

**Comment by rickhumphries** [comment]
Yeh sure - just making a vid now

**Comment by rickhumphries** [comment]
https://youtu.be/8F2eh7paBzY

**Comment by michael-collins** [comment]
@rickhumphries Looks like wrapping it with that class was useless. @btopro How do I fix the template?

**Comment by btopro** [comment]
@rickhumphries in your video, you don't choose the last option, have you tried it? This embeds without an iframe and instead just directly uses src. The wrapper in the video appears to be working to correctly resize the iframe, but if the image inside the iframe is set to certain dimensions then it won't matter.

So, this could be 2 things. 1, renaming the bottom option / highlighting it some how (we still need a "embed this" kind of button instead of what it is currently).  The 2nd is to make things wrapped somehow so that if the iframe changes the image inside reacts to the window its in. I do this w/ video (and that trick collins showed looks like it works too for video, obviously not images).

Try the last option if you haven't w/ the wrapper and let me know if that helps; that actually pulls it in locally.


Also, it's awesome seeing how fast your instance is as its cloud powered :)

**Comment by rickhumphries** [comment]
Yeh cloud powered all the way :+1: 

I've tried the last shortcode option but it's not pulling it across properly (screenshot attached) - maybe it's something to do with setting in course-outline or something though?

![image](https://cloud.githubusercontent.com/assets/4973810/7745888/48fe9a96-ffa6-11e4-9efb-0f9a5a46b0ad.png)

**Comment by btopro** [comment]
can you copy and paste what the broken link is as well as what the shortcode is please?

**Comment by rickhumphries** [comment]
The link to the image on media is:
`http://media.buttercups.orangebusstaging.co.uk/content/customer-service-delivery-drivers-welcome-image`

iframe code is 
`<iframe width="100%" height="300" src="http://media.buttercups.orangebusstaging.co.uk/entity_iframe/node/22" frameborder="0" class="entity_iframe entity_iframe_node" id="entity_iframe_node_22"></iframe>`

Small shortcode is
`[ciscode|rev=1|tool=elmsmedia|item=22]`

Long shortcode is (which is the one that's used in the image above)
`[ciscode|rev=1|tool=elmsmedia|item=22|render=link|field=field_image|text=Customer Service for Delivery Drivers Welcome Image|delta=0|item_type=image|alt=Customer Service for Delivery Drivers Welcome Image|width=950|height=438]`

Let me know if you need anything else

**Comment by btopro** [comment]
hmm.. mine just turned it into a link, need to dig deeper; will work on this today because I think I got the roles thing almost done.

**Comment by btopro** [comment]
Ok, tracked this down in one of my own instances. I've made a tweak to the code that will account for and squash this if it pops up. What's happening is the request for data goes out on a different URL then what's displayed (for security reasons). As a result (and it shouldn't happen) it appears that it's giving the file a path that's relative to if the file was uploaded to the media system, but via the service url. If you right clicked the image I bet you'd see something like media..../sites/media/services/{something}/files/filename.

So, code repo will have a fix for it, short term fix (and it will sound really stupid).

In the media system go to admin/config/media/file-system
Verify this doesn't have the word services in it (it shouldn't). Hit save.

Go back to the node / course that has the image embedded, edit the page and just hit save. See if it shows up now. It did for me.

**Comment by rickhumphries** [comment]
OK nice, one. Think I'll need to wait till we update core again - might actually be for v0.1 - but I can live with that for now :)
