### ISSUE TITLE
Blank page after login

### ISSUE THREAD

**Issue by kfurst** [btopro/elmsln#75]
I had to add /users/admin to the URL to get a space to log in. After logging in, I get a blank white page. I tried the other nodes/pages referenced in your install video, same result. This includes the linked items like help, take a tour, etc. 

I installed using vagrant per instructions in YouTube Tutorial.

**Comment by btopro** [comment]
Thank you for the report.

At the moment, go to http://online.elmsln.local/cis-quick-setup
If you enable the "CIS Theme" it should at least have areas to point to for what to do.

I'm spinning up vagrant and will debug soon. We're mid migration to the new user experience which has been applied to all new systems as the default but there are still UX needed obviously :). The Course Outline service is the most well developed at this time when you get to the (way too long) request page to build out a space.

**Comment by kfurst** [comment]
Thanks for the instant response. Unfortunately it didn't get me anywhere. I received the same "ACCESS DENIED" page I get when I go to online.elmsln.local. I've attached some images. I'll just wait until you get a chance to do some testing. No worries. 


Thanks for your help. 


![screen shot 2015-05-22 at 8 26 41 am](https://cloud.githubusercontent.com/assets/10422744/7771406/be7b25a8-005c-11e5-8572-69dac280d37a.png)
![screen shot 2015-05-22 at 8 26 27 am](https://cloud.githubusercontent.com/assets/10422744/7771407/be845d26-005c-11e5-9089-1a1c17bf4111.png)
![screen shot 2015-05-22 at 8 26 52 am](https://cloud.githubusercontent.com/assets/10422744/7771408/be84ae02-005c-11e5-9514-c3725abc72c2.png)
![screen shot 2015-05-22 at 8 26 12 am](https://cloud.githubusercontent.com/assets/10422744/7771409/be8951be-005c-11e5-9e97-f1a6e6630279.png)

**Comment by btopro** [comment]
very helpful thank you.

So from terminal where you did the vagrant up command to spin this up:
`vagrant ssh
drush @online uli`

This will generate a one-time login link for the online site which you can copy and paste into the address bar to log in.

**Comment by kfurst** [comment]
That worked to get me into the backend. All of the menu items for Drupal work (i.e. I can make changes, save, view, etc.) However, I'm still stuck in the same situation regarding the front end.  Interestingly, I got a warning upon save regarding 404s for some of those other local URLs. I went back and checked the etc/host file to ensure those addresses are added as per the instructions and they are there. I went back and looked at the logging from the install and saw the same 404s as failures during the install. (See below). Is this somehow connected to the issue? I looked for other failures during install and this is what I came up with. 

![screen shot 2015-05-22 at 9 14 32 am]
(https://cloud.githubusercontent.com/assets/10422744/7772664/337c4ece-0065-11e5-9431-a887db8b062a.png)
![screen shot 2015-05-22 at 9 18 47 am](https://cloud.githubusercontent.com/assets/10422744/7772663/3378f6fc-0065-11e5-95d9-6e93b6a9eecc.png)
![screen shot 2015-05-22 at 9 19 38 am](https://cloud.githubusercontent.com/assets/10422744/7772661/3375e430-0065-11e5-91f2-23e55bc2d0eb.png)
![screen shot 2015-05-22 at 9 20 18 am](https://cloud.githubusercontent.com/assets/10422744/7772662/3376b98c-0065-11e5-88d6-410feb980cde.png)

**Comment by btopro** [comment]
I see what's happening; This is a bandaid for now --
`d @online en cis_section`

And it'll start working. We're working on how calls for "hey give me the section" work when in the CIS because there's currently a lack of section context there (in the course spaces / other systems, absolutely there is).

We're debating if we use cis_section everywhere or provide a different type of support in authority systems like the CIS (Authorities are single drupal sites, Services are like each part of a course having a system to use).

**Comment by kfurst** [comment]
Yep, works. Thx.

**Comment by btopro** [comment]
Nice, setting the homepage to the cis-quick-setup page though you'll still need to log in after the first time so while this issue is fixed we still have UX / workflow stuff to do!
